language: node_js
node_js:
  - "node"
  - "6.9"

services: mongodb

install:
  - npm run heroku-prebuild

script:
  - npm test

after_script:
  - npm run heroku-postbuild

cache:
  directories:
    - node_modules
